export default [
    {
        title:'首页',
        key:'/admin/home5'
    },
    {
        title:'ui',
        key:'/admin/ui',
        children:[
            
            {
                title:'按钮',
                key:'/admin/ui/button'
            },
            {
                title:'弹窗',
                key:'/admin/ui/modals'
            },
            {
                title:'样式',
                key:'/admin/home3'
            },
            {
                title:'特效',
                key:'/admin/home4'
            },
            {
                title:'炫酷',
                key:'/admin/home5'
            },
        ]
        
    },
    {
        title:'首页',
        key:'/admin/home587888'
    },
    {
        title:'首页',
        key:'/admin/home5871'
    },
    {
        title:'首页',
        key:'/admin/home57'
    },
    {
        title:'首页',
        key:'/admin/home58477'
    },
    {
        title:'首页',
        key:'/admin/home58781'
    },
    {
        title:'首页',
        key:'/admin/home577'
    },
]